/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IGU;

/**
 *
 * @author lucquifer
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        PanelCeleste = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        nombreEnter = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        apellidoEnter = new javax.swing.JTextField();
        Cel = new javax.swing.JLabel();
        celEnter = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        correoEnter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCeleste.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout PanelCelesteLayout = new javax.swing.GroupLayout(PanelCeleste);
        PanelCeleste.setLayout(PanelCelesteLayout);
        PanelCelesteLayout.setHorizontalGroup(
            PanelCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        PanelCelesteLayout.setVerticalGroup(
            PanelCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        Background.add(PanelCeleste, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 160, 500));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Agenda Electronica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        Nombre.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre");
        Background.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 80, 30));
        Background.add(nombreEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 130, -1));

        Apellido.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Apellido.setForeground(new java.awt.Color(0, 0, 0));
        Apellido.setText("Apellido");
        Background.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 80, 30));
        Background.add(apellidoEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 130, -1));

        Cel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Cel.setForeground(new java.awt.Color(0, 0, 0));
        Cel.setText("Cel");
        Background.add(Cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 40, 30));
        Background.add(celEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 130, -1));

        Correo.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Correo.setForeground(new java.awt.Color(0, 0, 0));
        Correo.setText("Correo");
        Background.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 70, 30));
        Background.add(correoEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Cel;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel PanelCeleste;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField apellidoEnter;
    private javax.swing.JTextField celEnter;
    private javax.swing.JTextField correoEnter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreEnter;
    // End of variables declaration//GEN-END:variables
}
