/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IGU;

import Logica.Controladora;

/**
 *
 * @author lucquifer
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    // Variable global
Controladora control;
    
    
    public Principal(Controladora control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        clienteN = new javax.swing.JLabel();
        txtClienteEnter = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        txtNombreEnter = new javax.swing.JTextField();
        peluqueriaCanina = new javax.swing.JLabel();
        txtRazaEnter = new javax.swing.JTextField();
        raza = new javax.swing.JLabel();
        txtColorEnter = new javax.swing.JTextField();
        color = new javax.swing.JLabel();
        alergico = new javax.swing.JLabel();
        txtAlergicoEnter = new javax.swing.JComboBox<>();
        atencion = new javax.swing.JLabel();
        txtAtencionEnter = new javax.swing.JComboBox<>();
        txtCelularDuenioEnter = new javax.swing.JTextField();
        celularDuenio = new javax.swing.JLabel();
        nombreDuenio = new javax.swing.JLabel();
        txtNombreDuenioEnter = new javax.swing.JTextField();
        observaciones = new javax.swing.JLabel();
        txtObservacionesEnter = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteN.setBackground(new java.awt.Color(255, 255, 255));
        clienteN.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        clienteN.setForeground(new java.awt.Color(102, 102, 102));
        clienteN.setText("Cliente N°:");
        Background.add(clienteN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        txtClienteEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteEnterActionPerformed(evt);
            }
        });
        Background.add(txtClienteEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 170, -1));

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(102, 102, 102));
        Nombre.setText("Nombre:");
        Background.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        txtNombreEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEnterActionPerformed(evt);
            }
        });
        Background.add(txtNombreEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 170, -1));

        peluqueriaCanina.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        peluqueriaCanina.setForeground(new java.awt.Color(102, 102, 102));
        peluqueriaCanina.setText("PELUQUERIA CANINA");
        Background.add(peluqueriaCanina, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 240, 50));

        txtRazaEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaEnterActionPerformed(evt);
            }
        });
        Background.add(txtRazaEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 170, -1));

        raza.setBackground(new java.awt.Color(255, 255, 255));
        raza.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        raza.setForeground(new java.awt.Color(102, 102, 102));
        raza.setText("Raza:");
        Background.add(raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        txtColorEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorEnterActionPerformed(evt);
            }
        });
        Background.add(txtColorEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 170, -1));

        color.setBackground(new java.awt.Color(255, 255, 255));
        color.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        color.setForeground(new java.awt.Color(102, 102, 102));
        color.setText("Color:");
        Background.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        alergico.setBackground(new java.awt.Color(255, 255, 255));
        alergico.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        alergico.setForeground(new java.awt.Color(102, 102, 102));
        alergico.setText("Es Alergico:");
        Background.add(alergico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        txtAlergicoEnter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Si", "No" }));
        txtAlergicoEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergicoEnterActionPerformed(evt);
            }
        });
        Background.add(txtAlergicoEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 170, -1));

        atencion.setBackground(new java.awt.Color(255, 255, 255));
        atencion.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        atencion.setForeground(new java.awt.Color(102, 102, 102));
        atencion.setText("Atencion Especial:");
        Background.add(atencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        txtAtencionEnter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Si", "No" }));
        txtAtencionEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtencionEnterActionPerformed(evt);
            }
        });
        Background.add(txtAtencionEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 170, -1));

        txtCelularDuenioEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularDuenioEnterActionPerformed(evt);
            }
        });
        Background.add(txtCelularDuenioEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 170, -1));

        celularDuenio.setBackground(new java.awt.Color(255, 255, 255));
        celularDuenio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        celularDuenio.setForeground(new java.awt.Color(102, 102, 102));
        celularDuenio.setText("Celular del dueño:");
        Background.add(celularDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        nombreDuenio.setBackground(new java.awt.Color(255, 255, 255));
        nombreDuenio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        nombreDuenio.setForeground(new java.awt.Color(102, 102, 102));
        nombreDuenio.setText("Nombre del Dueño:");
        Background.add(nombreDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        txtNombreDuenioEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDuenioEnterActionPerformed(evt);
            }
        });
        Background.add(txtNombreDuenioEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 170, -1));

        observaciones.setBackground(new java.awt.Color(255, 255, 255));
        observaciones.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        observaciones.setForeground(new java.awt.Color(102, 102, 102));
        observaciones.setText("Observaciones:");
        Background.add(observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        txtObservacionesEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionesEnterActionPerformed(evt);
            }
        });
        Background.add(txtObservacionesEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 170, 140));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        Background.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        Background.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/Canino Modificado.jpg"))); // NOI18N
        Background.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteEnterActionPerformed

    private void txtNombreEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEnterActionPerformed

    private void txtRazaEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaEnterActionPerformed

    private void txtColorEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorEnterActionPerformed

    private void txtCelularDuenioEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularDuenioEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularDuenioEnterActionPerformed

    private void txtNombreDuenioEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDuenioEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDuenioEnterActionPerformed

    private void txtObservacionesEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionesEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionesEnterActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // Boton Guardar  ------------------------------------------------------------------
        int numeroClientePantalla =Integer.parseInt(txtClienteEnter.getText());
        String nombrePantalla = txtNombreEnter.getText();
        String razaPantalla = txtRazaEnter.getText();
        String colorPantalla = txtColorEnter.getText();
        
        
        String alergicoPantalla = (String)txtAlergicoEnter.getSelectedItem();
        String atencionPantalla = (String)txtAtencionEnter.getSelectedItem();
        
         
        String duenioPantalla =txtNombreDuenioEnter.getText();
        int celularPantalla =  Integer.parseInt(txtCelularDuenioEnter.getText());
        String observacionesPantalla = txtObservacionesEnter.getText();

        //
        control.altaPerro(numeroClientePantalla , nombrePantalla , razaPantalla , colorPantalla , alergicoPantalla , atencionPantalla , duenioPantalla , celularPantalla , observacionesPantalla);

        // Fin boton guardar  ----------------------------------------------------------------
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        //Seteamos todo en 0
        txtClienteEnter.setText("");
        txtNombreEnter.setText("");
        txtRazaEnter.setText("");
        txtColorEnter.setText("");
        txtAlergicoEnter.setSelectedItem("-");
        txtAtencionEnter.setSelectedItem("-");
        txtNombreDuenioEnter.setText("");
        txtCelularDuenioEnter.setText("");
        txtObservacionesEnter.setText("");
        

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtAlergicoEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergicoEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergicoEnterActionPerformed

    private void txtAtencionEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtencionEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtencionEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel alergico;
    private javax.swing.JLabel atencion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel celularDuenio;
    private javax.swing.JLabel clienteN;
    private javax.swing.JLabel color;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel nombreDuenio;
    private javax.swing.JLabel observaciones;
    private javax.swing.JLabel peluqueriaCanina;
    private javax.swing.JLabel raza;
    private javax.swing.JComboBox<String> txtAlergicoEnter;
    private javax.swing.JComboBox<String> txtAtencionEnter;
    private javax.swing.JTextField txtCelularDuenioEnter;
    private javax.swing.JTextField txtClienteEnter;
    private javax.swing.JTextField txtColorEnter;
    private javax.swing.JTextField txtNombreDuenioEnter;
    private javax.swing.JTextField txtNombreEnter;
    private javax.swing.JTextField txtObservacionesEnter;
    private javax.swing.JTextField txtRazaEnter;
    // End of variables declaration//GEN-END:variables
}
