/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu;

/**
 *
 * @author lucquifer
 */
public class Principal extends javax.swing.JFrame {

    public static String[] listaDni = new String[10];
    public static String[] listaNombre = new String[10];
    public static String[] listaApellido = new String[10];
    public static String[] listaDireccion = new String[10];
    public static String[] listaTelefono = new String[10];
    public static String[] listaFecha = new String[10];
    public static int i = 0;
    public static int uAt = 0;
    public static int uAd = 0;
    public static int max = 0;
    public static int pos = 0;

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnGuadar = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 73, 594, 10));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 48)); // NOI18N
        jLabel1.setText("Agenda Electronica");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 4, 491, -1));

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 134, 120, -1));

        jLabel2.setText("D.N.I.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 138, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 175, 120, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 179, -1, -1));

        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 220, -1, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 216, 120, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 134, 120, -1));

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 138, -1, -1));

        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 179, -1, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 175, 120, -1));

        jLabel7.setText("Fecha de Nac.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 220, -1, -1));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 216, 120, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 272, 594, 10));

        btnGuadar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Guardar.png"))); // NOI18N
        btnGuadar.setText("   Guardar");
        btnGuadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuadarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuadar, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 300, 144, 39));

        btnAdelante.setText(">>");
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 308, -1, -1));

        btnAtras.setText("<<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 308, -1, -1));

        jLabel8.setText("Indice");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 384, -1, -1));

        txtIndice.setEditable(false);
        jPanel1.add(txtIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 380, 26, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 443, 594, 10));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom_38542.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 371, 137, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        uAt = pos;
        if (uAt > 0) {
            uAt--;
            txtDni.setText(listaDni[uAt]);
            txtNombre.setText(listaNombre[uAt]);
            txtApellido.setText(listaApellido[uAt]);
            txtDireccion.setText(listaDireccion[uAt]);
            txtTelefono.setText(listaTelefono[uAt]);
            txtFecha.setText(listaFecha[uAt]);
            txtIndice.setText(" " + uAt + "");
            pos = uAt;
        } else {
            txtDni.setText(listaDni[0]);
            txtNombre.setText(listaNombre[0]);
            txtApellido.setText(listaApellido[0]);
            txtDireccion.setText(listaDireccion[0]);
            txtTelefono.setText(listaTelefono[0]);
            txtFecha.setText(listaFecha[0]);
            txtIndice.setText("0");
            pos = uAt;
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        uAd = pos;
        if (uAd < max) {
            uAd++;
            txtDni.setText(listaDni[uAd]);
            txtNombre.setText(listaNombre[uAd]);
            txtApellido.setText(listaApellido[uAd]);
            txtDireccion.setText(listaDireccion[uAd]);
            txtTelefono.setText(listaTelefono[uAd]);
            txtFecha.setText(listaFecha[uAd]);
            txtIndice.setText(" " + uAd + "");
            pos = uAd;
        } else {
            txtDni.setText(listaDni[max]);
            txtNombre.setText(listaNombre[max]);
            txtApellido.setText(listaApellido[max]);
            txtDireccion.setText(listaDireccion[max]);
            txtTelefono.setText(listaTelefono[max]);
            txtFecha.setText(listaFecha[max]);
            txtIndice.setText(" " + max + "");
            pos = uAd;
        }
    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void btnGuadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuadarActionPerformed

        if (i < 10) {
            listaDni[i] = txtDni.getText();
            listaNombre[i] = txtNombre.getText();
            listaApellido[i] = txtApellido.getText();
            listaDireccion[i] = txtDireccion.getText();
            listaTelefono[i] = txtTelefono.getText();
            listaFecha[i] = txtFecha.getText();
            pos = i;
            max = i;
            i++;
            //--------------------------------------------------------------------------------------------------------------------------------------
            // Limpia Pantalla
            txtDni.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtDireccion.setText("");
            txtDni.setText("");
            txtTelefono.setText("");
            txtFecha.setText("");
        }
    }//GEN-LAST:event_btnGuadarActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //--------------------------------------------------------------------------------------------------------------------------------------
        // Limpia Pantalla
        txtDni.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtDni.setText("");
        txtTelefono.setText("");
        txtFecha.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuadar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
